name: infospect
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.2
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  cuberto_bottom_bar: ^2.0.0
  desktop_multi_window: ^0.2.0
  dio: ^5.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_json_view: 1.1.2
  font_awesome_flutter: ^10.5.0
  http: ^1.1.0
  meta: ^1.9.1
  package_info_plus: ^4.0.2
  path: ^1.8.3
  rxdart: ^0.27.7
  share_plus: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.4


flutter:
