name: infospect
description: Infospect meaning Information Inspector is a Flutter plugin for that empowers the developers to debug the network calls and logs in the app.
version: 0.1.1
repository: https://github.com/kushalmahapatro/infospect
topics:
  - interceptor
  - dio
  - http
  - information-inspector
  - multi-window

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

screenshots:
  - description: 'Infospect Desktop Multi Window- macOS'
    path: images/screenshot/desktop_multi_window.png
  - description: 'Infospect Desktop Multi Window- Linux'
    path: images/screenshot/linux.png
  - description: 'Infospect Desktop Multi Window- Windows'
    path: images/screenshot/windows.png
  - description: 'Infospect network calls screen - Mobile'
    path: images/screenshot/network_calls_screen.png
  - description: 'Infospect logs screen - Mobile'
    path: images/screenshot/logs.png
  - description: 'Infospect network calls screen - Desktop'
    path: images/screenshot/network_calls_screen_desktop.png
  - description: 'Infospect logs screen - Desktop'
    path: images/screenshot/logs_desktop.png
  - description: 'Infospect invoker open state'
    path: images/screenshot/expanded.png
  - description: 'Infospect share UI - Mobile'
    path: images/screenshot/share.png
  - description: 'Infospect share UI - Desktop'
    path: images/screenshot/share_desktop.png


dependencies:
  # sdk
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  archive: ^3.3.7
  bloc: ^8.1.2
  collection: ^1.17.1
  cuberto_bottom_bar: ^2.0.0
  cupertino_icons: ^1.0.2
  desktop_multi_window: ^0.2.0
  dio: ^5.3.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_json_view: ^1.1.2
  font_awesome_flutter: ^10.5.0
  http: ^1.1.0
  menu_bar: ^0.5.3
  meta: ^1.9.1
  package_info_plus: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.1.0
  rxdart: ^0.27.7
  share_plus: ^7.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.4
  lints: ^2.1.1

